### ISSUE TITLE
Problem with ooVooNotifications

### ISSUE THREAD

**Issue by bercik0291** [oovoodev/iOS-SDK-Sample#11]
Hi,

There is some problem with ooVoo notifications when you would like to start new video conference. I don't get information that second user has joined to conference (conference ID is the same for both). What is more I don't always have neither my preview nor camera of second user (I have black screen for this only). Moreover sometimes I get notifications with error but there is only ooVooErrorKey without any description about that. For example I get error on OOVOOVideoTransmitDidStartNotification with ooVooErrorKey = 3. When it happens, nothing is working.

Would you describe me each of code errors because I would like to know what is wrong with it?

**Comment by eakraly** [comment]
Hi bercik0291,
Somehow we missed some of the issues here. Is this issue still relevant?

**Comment by alexwillingham** [comment]
Hello,

I've been having similar issues.  On bad networks, incoming video feed(s) appear black.  I searched for ooVooErrorKey = 3 as referenced above and stumbled upon this recently closed (yet unresolved?) issue.

Logging these notifications gives:

OOVOOVideoTransmitDidStartNotification: {
    OOVOOErrorKey = 3;
}

or another example,

OOVOOUserDidMuteMicrophoneNotification: {
    OOVOOErrorKey = 5;
}

These ErrorKey codes, you can imagine, are not particularly useful to SDK users without insight into the enum identifying what these errors mean.

I'm not entirely convinced, unlike @bercik0291 , that this ooVooErrorKey=3 notification is related to the case where I I do not receive incoming video streams, but I would like very much to understand two things:

1) What do these error keys mean and how should one typically handle them?  

2) How to detect that the network is bad enough on one end that incoming video feeds are not being displayed at all.  This would be helpful as it would allow me to disconnect from the conference and explain the situation to the user instead of them just seeing black feeds and being confused.

Thanks in advance!  If this issue doesn't re-open shortly I'll make a new one.

**Comment by eakraly** [comment]
Hi @alexwillingham,

You can find error code description in our developer documentation. I'll provide it here for your convenience - even though some of them could still be obscure. 
In the next release we will add the description into the notification.

0\. OK
1. InvalidParameter
2. InvalidPointer
3. InvalidOperation
4. MethodNotImplemented
5. DeviceNotFound
6. AlreadyInSession
7. DuplicateParticipantId
8. ConferenceIdNotValid
9. ClientIdNotValid
10. ParticipantIdNotValid
11. CameraIdNotValid
12. MicrophoneIdNotValid
13. SpeakerIdNotValid
14. VolumeNotValid
15. ServerAddressNotValid
16. GroupQuotaExceeded
17. NotInitialized
18. Error
19. NotAuthorized
20. ConnectionTimeout
21. DisconnectedByPeer
22. InvalidToken
23. ExpiredToken
24. PreviousOperationNotCompleted
25. AppIdNotValid
26. NoAvs
27. ActionNotPermitted
28. DeviceNotInitialized
29. Held
30. SSLCertificateVerificationFailed
31. NetworkReconnected

**Comment by dmabram** [comment]
Can you provide a link or pointer as to where I might find the documentation you reference?  Searching the available online docs doesn't seem to turn up anything.

**Comment by eranmalovany** [comment]
Hi,

The documentation is available in the doc folder which is part of the bundle.
anyway please refer to the list above.
we are working to make the documentation much more user friendly and it will be available with the next release.
meanwhile, let us know if you have any issue, you can also open ticket directly from the developers dashboard.

**Comment by alexwillingham** [comment]
Thanks for the above list, we'll refer to it.

I'd like to share what the .framework bundle contains for me.  Headers/ with 4 .h files, and the framework binary.  I'd really like to see all the documentation that I can; Is it available somewhere for consumers of the SDK?

![image](https://cloud.githubusercontent.com/assets/3759688/7632499/c57ba11c-fa1b-11e4-8c85-d75de8866723.png)

**Comment by eranmalovany** [comment]
OK, got you.
Please download the bundle from our website,  use your credentials to login, you will be redirect to the dashboard, click on download SDK and download the relevant bundle, then unzip it, you will find the docs in the docs folder.

![image](https://cloud.githubusercontent.com/assets/3629370/7632634/b2862f50-fa57-11e4-993d-b4f4188872ab.png)

**Comment by alexwillingham** [comment]
Thanks for your help, but we're still not quite matching up.  The doc bundled alongside the iOS framework is just a PDF of the documentation available here https://developer.oovoo.com/docs -> iOS

I've studied that documentation thoroughly, and it doesn't have the error codes table pasted above.  I'm wondering where that table is documented so that I can look at the other documentation there.

**Comment by eranmalovany** [comment]
Ok.
keep using the list you got and we will make sure it will be available in the next release in addition to the description of the error.

**Comment by divyamML** [comment]
do we know what could be the potential reasons for 

OOVOOVideoTransmitDidStartNotification: {
OOVOOErrorKey = 3;
}
